name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup C++ toolchain
      uses: miro011/setup-cmake@v2

    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build C++ & Python extension
      run: cmake --build build --parallel

    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Run Python tests
      run: pytest -q
