# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake python3-dev python3-pip

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip install pybind11 numpy click pytest

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build C++ core and Python extension
      run: cmake --build build --config Release -- -j$(nproc)

    - name: Install package
      run: pip install .

    - name: Run tests
      run: pytest -q
